è# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gepafer_wrappers", use_symbols = TRUE, package_name = "gepafer")

#' @usage NULL
#' @useDynLib gepafer, .registration = TRUE
NULL

#' Encode coordinates to polyline.
#' @export
encode_coordinates <- function(coords, factor) .Call(wrap__encode_coordinates, coords, factor)

#' Decode coordinates
#' @export
decode_coordinates <- function(polyline, factor) .Call(wrap__decode_coordinates, polyline, factor)


# nolint end
