# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gepafer_wrappers", use_symbols = TRUE, package_name = "gepafer")

#' @docType package
#' @usage NULL
#' @useDynLib gepafer, .registration = TRUE
NULL

#' Encode coordinates to polyline.
#' @export
encode_polyline <- function(coords, factor) .Call(wrap__encode_polyline, coords, factor)

#' Decode coordinates
#' @export
decode_polyline <- function(polyline, factor) .Call(wrap__decode_polyline, polyline, factor)


# nolint end
